-- 1. Create Profiles table (Extensions of Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  paid_until timestamptz default null, -- The manual switch
  created_at timestamptz default now()
);

-- 2. Create Questions table
create table public.questions (
  id bigint generated by default as identity primary key,
  category text default 'Gastroenterology',
  question_text text not null,
  image_url text, -- Placeholder for X-rays/CTs
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null, -- 'A', 'B', 'C', 'D'
  explanation text not null,
  created_at timestamptz default now()
);

-- 3. Enable RLS
alter table public.profiles enable row level security;
alter table public.questions enable row level security;

-- 4. Policies
-- Users can read their own profile
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

-- Anyone (authenticated) can read questions, usually you'd filter this based on paid status in app logic or here
create policy "Auth users can read questions" on public.questions
  for select using (auth.role() = 'authenticated');

-- 5. Trigger to create profile on signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. SEED DATA: 10 EHPLE Style Gastro MCQs
INSERT INTO public.questions (question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
(
  'A 45-year-old male presents with hematemesis. Endoscopy reveals esophageal varices. Which of the following is the mechanism of action of the drug of choice for acute management?',
  'Proton pump inhibition',
  'Splanchnic vasoconstriction',
  'Beta-adrenergic blockade',
  'Antibiotic prophylaxis',
  'B',
  'Octreotide (somatostatin analog) causes splanchnic vasoconstriction, reducing portal inflow and variceal pressure.'
),
(
  'Which of the following serological markers indicates a high level of viral replication and infectivity in a patient with Hepatitis B?',
  'HBsAg',
  'Anti-HBs',
  'HBeAg',
  'Anti-HBc IgM',
  'C',
  'HBeAg (Envelope antigen) correlates with active viral replication and high infectivity.'
),
(
  'A 30-year-old female complains of dysphagia to both solids and liquids. Barium swallow shows a "bird-beak" appearance. What is the most likely diagnosis?',
  'Esophageal Web',
  'Zenker Diverticulum',
  'Achalasia',
  'Esophageal Cancer',
  'C',
  'Achalasia is characterized by aperistalsis and failure of LES relaxation, leading to the bird-beak sign.'
),
(
  'Which of the following is the most specific non-invasive test for H. pylori diagnosis?',
  'Serology (IgG)',
  'Urea Breath Test',
  'Stool Antigen Test',
  'Rapid Urease Test (Biopsy)',
  'B',
  'The Urea Breath Test is highly specific and sensitive for active infection, unlike serology which cannot distinguish past from current infection.'
),
(
  'A patient with ascites has a PMN count of 350 cells/mm3 in the ascitic fluid. What is the indicated treatment?',
  'Therapeutic Paracentesis',
  'IV Cefotaxime',
  'Oral Furosemide',
  'TIPS procedure',
  'B',
  'Spontaneous Bacterial Peritonitis (SBP) is diagnosed if PMN > 250. Immediate antibiotic treatment (3rd gen cephalosporin) is required.'
),
(
  'A 55-year-old male with long-standing GERD presents with weight loss. Biopsy shows columnar metaplasia of the distal esophagus. This condition predisposes to:',
  'Squamous cell carcinoma',
  'Adenocarcinoma',
  'Lymphoma',
  'Leiomyoma',
  'B',
  'Barrett’s esophagus (columnar metaplasia) is a major risk factor for Esophageal Adenocarcinoma.'
),
(
  'In a patient with severe acute pancreatitis, which electrolyte abnormality implies a poor prognosis (Ranson Criteria)?',
  'Hyperkalemia',
  'Hypocalcemia',
  'Hypernatremia',
  'Hypomagnesemia',
  'B',
  'Hypocalcemia (< 8 mg/dL) indicates saponification of fat (severe necrosis) and is a poor prognostic sign.'
),
(
  'Which dermatological finding is associated with Celiac Disease?',
  'Erythema Nodosum',
  'Pyoderma Gangrenosum',
  'Dermatitis Herpetiformis',
  'Acanthosis Nigricans',
  'C',
  'Dermatitis Herpetiformis is an intensely pruritic papulovesicular rash pathognomonic for Celiac Disease.'
),
(
  'First-line treatment for Hepatic Encephalopathy involves:',
  'Restricting protein intake strictly',
  'Lactulose',
  'Neomycin',
  'IV Albumin',
  'B',
  'Lactulose acidifies the gut lumen, converting NH3 to NH4+ (ammonium), which is trapped and excreted.'
),
(
  'A 25-year-old male presents with bloody diarrhea and lower abdominal pain. Colonoscopy shows continuous inflammation starting from the rectum. Diagnosis?',
  'Crohn’s Disease',
  'Ulcerative Colitis',
  'Ischemic Colitis',
  'Irritable Bowel Syndrome',
  'B',
  'Ulcerative Colitis presents with continuous mucosal inflammation always involving the rectum and extending proximally.'
);
